# Layer 1.1: Bitget Spot Base
base_preset: base_crypto_spot.yaml
exchanges: ["BITGET"]

ensure_symbols:
- BITGET:BTCUSDT
- BITGET:ETHUSDT
- BITGET:SOLUSDT
- BITGET:ADAUSDT
- BITGET:DOGEUSDT
- BITGET:LINKUSDT
- BITGET:LTCUSDT
- BITGET:DOTUSDT
- BITGET:AVAXUSDT
- BITGET:TRXUSDT
