# Layer 1.1: Binance Perp Base
base_preset: base_crypto_perp.yaml
exchanges: ["BINANCE"]

ensure_symbols:
- BINANCE:BTCUSDT.P
- BINANCE:ETHUSDT.P
- BINANCE:SOLUSDT.P
- BINANCE:ADAUSDT.P
- BINANCE:DOGEUSDT.P
- BINANCE:LINKUSDT.P
- BINANCE:LTCUSDT.P
- BINANCE:DOTUSDT.P
- BINANCE:AVAXUSDT.P
- BINANCE:TRXUSDT.P
- BINANCE:BNBUSDT.P
- BINANCE:XRPUSDT.P
- BINANCE:MATICUSDT.P
- BINANCE:TRXUSDT.P
