# Binance Spot - Oscillator Rating - SHORT
base_preset: ../../../base/universes/binance_spot_base.yaml
metadata:
  intent: "SHORT"
sort_by: Recommend.All|240
sort_order: desc
limit: 100
export_metadata:
  symbol: spot_rating_osc_short
  data_category: strategy_alpha
