# Binance Spot - All Rating - LONG
base_preset: ../../../base/universes/binance_spot_base.yaml
metadata:
  intent: "LONG"
filters:
  - { left: "Recommend.All", operation: "greater", right: 0 }
limit: 100
export_metadata:
  symbol: spot_rating_all_long
  data_category: strategy_alpha
