# Binance Perp - binance_perp_rating_osc_long
base_preset: ../../../base/universes/binance_perp_base.yaml
metadata:
  intent: "LONG"
filters:
  - { left: "Recommend.Other", operation: "greater", right: 0 }
sort_by: Recommend.All|240
sort_order: desc
limit: 100
export_metadata:
  symbol: perp_rating_osc_long
  data_category: strategy_alpha
