# Binance Spot - Oscillator Rating - LONG
base_preset: ../../../base/universes/binance_spot_base.yaml
metadata:
  intent: "LONG"
sort_by: Recommend.All|240
sort_order: desc
limit: 100
export_metadata:
  symbol: spot_rating_osc_long
  data_category: strategy_alpha
