# Binance Perp - binance_perp_rating_all_short
base_preset: ../../../base/universes/binance_perp_base.yaml
metadata:
  intent: "SHORT"
filters:
  - { left: "Recommend.All", operation: "less", right: 0 }
sort_by: Recommend.All|240
sort_order: desc
limit: 100
export_metadata:
  symbol: perp_rating_all_short
  data_category: strategy_alpha
