# Binance Spot - MA Rating - SHORT
base_preset: ../../../base/universes/binance_spot_base.yaml
metadata:
  intent: "SHORT"
filters:
  - { left: "Recommend.MA", operation: "less", right: 0 }
limit: 100
export_metadata:
  symbol: spot_rating_ma_short
  data_category: strategy_alpha
