base_preset: ../../base/universes/bond_etfs.yaml
static_mode: true
static_symbols:
  - "AMEX:AGG"
  - "NASDAQ:BND"
  - "NASDAQ:TLT"
  - "AMEX:LQD"
  - "AMEX:HYG"
  - "NASDAQ:IEF"
  - "NASDAQ:SHY"
volume:
  value_traded_min: 0
trend:
  recommendation: {enabled: false}
  adx: {enabled: false}
  momentum: {enabled: false}
limit: 15
export_metadata:
  symbol: bond_etf_trend
  data_category: strategy_alpha
