# L0: Liquid Bond ETFs
base_preset: ../hygiene/institutional.yaml
markets: ["america"]
filters:
  - left: "type"
    operation: "equal"
    right: "etf"
  - left: "description"
    operation: "match"
    right: "Bond|Treasury|Fixed Income"
sort_by: "volume"
sort_order: "desc"
limit: 20
export_metadata:
  symbol: bond_etf_universe
  data_category: universe_foundation
